name: Publish docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REPO: ${{ github.repository }}
  IMAGE: ghcr.io/${{ github.repository }}
  
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Debugging
        run: |
          env | sort
          echo IMAGE_NAME: $IMAGE_NAME

      - name: Get last commit sha from pull request
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "LAST_COMMIT_SHA=${{ github.event.pull_request.head.sha }}" >> ${GITHUB_ENV}

      - name: Get last commit sha from push
        if: ${{ github.event_name == 'push' }}
        run: |
          echo "LAST_COMMIT_SHA=${GITHUB_SHA}" >> ${GITHUB_ENV}

      - name: Set tag
        run: |
          echo "TAG=${IMAGE}:${LAST_COMMIT_SHA}" >> ${GITHUB_ENV}
          echo "TAG=${IMAGE}:${LAST_COMMIT_SHA}"

      - name: Build and push Docker image
        run: |
          docker build . --tag $TAG
          docker push $TAG

      - name: Push latest tag
        if: ${{ github.event_name == 'push' }}
        run: |
          docker tag $TAG $IMAGE:latest
          docker push $IMAGE:latest

